-- AlterTable
ALTER TABLE `constructions` ADD COLUMN `periority` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `type` ENUM('INDIVIDUAL', 'GROUP') NULL,
    MODIFY `status` ENUM('PENDING', 'PROCESSING', 'WAITING', 'DONE', 'CANCELLED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `employees` ADD COLUMN `type` ENUM('INDIVIDUAL', 'GROUP') NOT NULL DEFAULT 'INDIVIDUAL';

-- AlterTable
ALTER TABLE `orders` MODIFY `status` ENUM('PENDING', 'PROCESSING', 'WAITING', 'DONE', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
